name: note
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: 3.4.1
  bloc_concurrency: 0.2.2
  collection: 1.18.0
  cupertino_icons: 1.0.6
  flutter_bloc: 8.1.3
  flutter_hooks: 0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.9
  freezed_annotation: 2.4.1
  get_it: 7.6.4
  go_router: 12.1.1
  google_fonts: 6.1.0
  intl: 0.18.1
  injectable: 2.3.2
  shared_preferences: 2.2.2
  flutter_secure_storage: 7.0.1
  fpdart: 0.4.0
  animated_bottom_navigation_bar: 1.3.0
  sqflite: 2.3.0
  path_provider: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 5.13.0
  bloc_test: 9.1.5
  build_runner: 2.4.7
  envied_generator: 0.5.2
  freezed: 2.4.5
  lints: 3.0.0
  mockingjay: 0.5.0
  mocktail: 1.0.1
  platform: 3.1.3
  injectable_generator: 2.4.1
  flutter_lints: 3.0.1
  json_serializable: 6.6.0
  

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
